// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "amplifyjsapp-20181025232055--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://amplifyjsapp-20181025232055--hostingbucket.s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:e476bce2-36a4-4140-b93c-067cd71902a2",
    "aws_cognito_region": "eu-west-1",
    "aws_mobile_analytics_app_id": "458fbea7f48d4694b654b91720252c4b",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
